# Generated by Django 5.1.2 on 2024-10-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('female', 'ผู้หญิง'), ('male', 'ผู้ชาย'), ('other', 'อื่นๆ')], max_length=10)),
                ('age_group', models.CharField(choices=[('under18', 'ต่ำกว่า 18'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('64+', '64 ขึ้นไป')], max_length=10)),
                ('favorite_types', models.ManyToManyField(blank=True, to='home.tourtype')),
            ],
        ),
    ]
